### ISSUE TITLE
error in low-health-alarm

### ISSUE THREAD

**Issue by migzlv** [AndrielChaoti/wow_low-health-alarm#4]
Hi
i get an error in low health alarm.
Message: ...ns\LowHealthAlarm\libs\AceEvent-3.0\AceEvent-3.0.lua:33: Attempt to register unknown event "UNIT_HEALTH_FREQUENT"
Time: Thu Apr 15 23:14:55 2021
Count: 1
Stack: ...ns\LowHealthAlarm\libs\AceEvent-3.0\AceEvent-3.0.lua:33: Attempt to register unknown event "UNIT_HEALTH_FREQUENT"
[string "=[C]"]: in function `RegisterEvent'
[string "@Interface\AddOns\LowHealthAlarm\libs\AceEvent-3.0\AceEvent-3.0.lua"]:33: in function `OnUsed'
[string "@Interface\AddOns\LowHealthAlarm\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:168: in function `RegisterEvent'
[string "@Interface\AddOns\LowHealthAlarm\init.lua"]:102: in function <Interface\AddOns\LowHealthAlarm\init.lua:93>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\LowHealthAlarm\libs\AceAddon-3.0\AceAddon-3.0.lua"]:558: in function `EnableAddon'
[string "@Interface\AddOns\LowHealthAlarm\libs\AceAddon-3.0\AceAddon-3.0.lua"]:651: in function <...ns\LowHealthAlarm\libs\AceAddon-3.0\AceAddon-3.0.lua:636>
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface\FrameXML\UIParent.lua"]:504: in function `UIParentLoadAddOn'
[string "@Interface\FrameXML\UIParent.lua"]:623: in function `TimeManager_LoadUI'
[string "@Interface\FrameXML\UIParent.lua"]:1392: in function <Interface\FrameXML\UIParent.lua:1277>

Locals: <none>

**Comment by AndrielChaoti** [comment]
I don't currently have a replacement for the event this error is referencing, i'll look into it.

**Comment by AndrielChaoti** [comment]
This should be fixed by PR #3
